backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('consultant.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'consultant.views.error_404'

consultant/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'consultant'

urlpatterns = [
    # path('', TemplateView.as_view(template_name='consultant/home.html'), name='home'),
    path('', views.interview_by_company, name='home'),
    path('create_interview/', views.create_interview, name='create_interview'),
    path('interview_questions_for_employee/<interview_id>/', views.interview_questions_for_employee, name='interview_questions_for_employee'),
    path('interview_by_company/', views.interview_by_company, name='interview_by_company'),
    path('interview_detail/<interview_id>/', views.interview_detail, name='interview_detail'),
    path('employee_detail/<employee_id>/<interview_id>/', views.employee_detail, name='employee_detail'),   
]

users/urls.py
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

consultant/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

class Company(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    is_finished = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.name
    
class JobInterview(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    employees = models.ManyToManyField(Employee)
    number_of_questions = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)])

    def __str__(self):
        return f'{self.company.name} Interviewed {self.employees.name}'
    
class Question(models.Model):
    interview = models.ForeignKey(JobInterview, on_delete=models.CASCADE, null=True, blank=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    question = models.CharField(max_length=100, null=True, blank=True)
    answer = models.CharField(max_length=100, null=True, blank=True)
    result = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.question

consultant/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Company, Employee, JobInterview, Question

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'email']

class JobInterviewForm(forms.ModelForm):
    class Meta:
        model = JobInterview
        fields = ['title', 'company', 'number_of_questions']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question', 'answer', 'result']

consultant/views.py
from django.shortcuts import render, redirect
from .models import Company, Employee, JobInterview, Question
from .forms import CompanyForm, EmployeeForm, JobInterviewForm, QuestionForm
import os
import openai
from conf.conf import OPENAI_API_KEY, api, customer_id, url
import re
import pandas as pd
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
import requests
from django.core.mail import EmailMessage
import threading


## Start Vetara
def get_respose_vectara(question):
    response = requests.post(
        url,
        headers={
            "Content-Type": "application/json",
            "customer-id": customer_id,
            "x-api-key": api
        },
        json={
            "model": "gpt-3.5-turbo",
            "messages": [
                {
                    "role": "user",
                    "content": question,
                }
            ]
        }
    )
    return response.json()['choices'][0]['message']['content']
### End Vetara

### Start OpenAI
openai.api_key = os.getenv("OPENAI_API_KEY", OPENAI_API_KEY)
def get_respose(question):
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt=question,
        temperature=0.7,
        max_tokens=512,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0.6
    )
    return response.choices[0].text

def questions(job_title, number_of_questions):
    questions = get_respose(f"Generate {number_of_questions} interview questions for job conditions of {job_title}.")
    pattern = r'\n'
    res = re.split(pattern, questions)
    return res

def rate_answer(question, answer):
    rate = get_respose(f"""### 
    # Rate the following answer of this question form (1 to 10), then return the rate as integer. if the answer is empty rate it 0.
    # Question: {question}.
    # Answer: {answer}.
### """)
    return int(rate)
### End OpenAI


### Start Excel file and pandas
def read_excel_file(file):
    df = pd.read_excel(file)
    if 'name' not in df.columns or 'email' not in df.columns or df.empty:
        return False
    # return list of dict contain name and email
    return df.to_dict('records')
### End Excel file and pandas




@login_required
def create_interview(request):
    if request.method == 'POST':
        job_title = request.POST.get('title')
        company = request.user.company_set.first().id
        number_of_questions = request.POST.get('number_of_questions')
        # read employees form excel file 
        employees = read_excel_file(request.FILES['employees'])

        # create interview
        interview = JobInterview.objects.create(title=job_title, company=Company.objects.get(id=company), number_of_questions=number_of_questions)
        for employee in employees:
            print(employee)
            try:
                user = User.objects.filter(email=employee['email']).last() # edit to last
                if user is None:
                    user = User.objects.create_user(username=employee['email'], email=employee['email'], password='123456')
                print(f"in try {user}")
            except:
                user = User.objects.create_user(username=employee['email'], email=employee['email'], password='123456')
                print(f"in except {user}")
            Employee.objects.create(user=user, name=employee['name'], email=employee['email'])
            interview.employees.add(Employee.objects.filter(name=employee['name']).last()) #edit to last
            # create questions for each employee
            for question in questions(job_title, number_of_questions)[2:]:
                Question.objects.create(interview=interview, question=question, employee=Employee.objects.filter(name=employee['name']).first())
        # send email to employees
        
        print("Now sent email to employees")
        for employee in employees:
            email = EmailMessage(
                subject='Interview',
                body=f'''Hi {employee["name"]}, you have an interview for {job_title} position, please click on the link to answer the questions: http://127.0.0.1:8000/interview_questions_for_employee/{interview.id}
                username is {employee["email"]}
                password is 123456
                ''',
                from_email="event@azzam.app",
                to=[employee['email']],
                headers={"Content-Type": "text/html"},
            )
            email.content_subtype = "html"
            email.send()
        # thread = threading.Thread(target=send_email_to_employees)
        # thread.start()
        
        
        return redirect(reverse_lazy('consultant:interview_by_company', )) 
        # return redirect(reverse_lazy('consultant:interview_by_company', kwargs={'company_id': company})) 
        # return render(request, 'consultant/create_interview.html', {'success': 'Interview created successfully'})        

    else:
        form = JobInterviewForm()
        companies = Company.objects.all()
    return render(request, 'consultant/create_interview.html', {'form': form, 'companies': companies, 'company_id': request.user.company_set.first().id})
    

@login_required
def interview_questions_for_employee(request, interview_id):
    employee_id = request.user.id
    employee = Employee.objects.filter(user=employee_id).last()
    questions = Question.objects.filter(interview=interview_id, employee=employee.id)
    interview = JobInterview.objects.filter(id=interview_id).first()
    print(employee.id, employee_id,)
    print(questions)
    print(dir(questions))

    # if interview.is_finished == False:
    print(employee.is_finished)
    if employee.is_finished == False:
        if request.method == 'POST':
            for question in questions:
                answer = request.POST.get("question"+str(question.id))
                # make update for question
                question.answer = answer
                question.result = rate_answer(question.question, answer)
                question.save()
                employee.is_finished = True
                employee.save()
            return render(request, 'consultant/done_questins.html', {'success': 'Interview completed successfully'})
        else:
            return render(request, 'consultant/interview_questions_for_employee.html', {'questions': questions, 'employee': employee})
    else:
        return render(request, 'consultant/done_questins.html', {'success': 'Interview completed successfully'})
    # return render(request, 'consultant/interview_questions_for_employee.html', {'questions': questions, 'employee': employee})


@login_required
def interview_detail(request, interview_id):
    interview = JobInterview.objects.filter(id=interview_id).first()
    employees = Employee.objects.filter(jobinterview=interview.id)
    return render(request, 'consultant/interview_detail.html', {'interview': interview, 'employees': employees})


@login_required
def employee_detail(request, employee_id, interview_id):
    try:
        interview = JobInterview.objects.filter(employees=employee_id, id=interview_id).first()
        if  interview.company.user.id != request.user.id:
            return redirect('consultant:home')
    except:
        return redirect('consultant:home')
    if  interview.company.user.id != request.user.id:
        return redirect('consultant:home')
    employee = Employee.objects.filter(id=employee_id).first()
    questions = Question.objects.filter(employee=employee_id, interview=interview_id)
    average_result = 0
    total_result = 0
    print(questions)
    for question in questions:
        if question.result != None:
            total_result += int(question.result)
    if len(questions) != 0:
        average_result = total_result / (len(questions) * 10) 
        average_result = average_result * 100
    return render(request, 'consultant/employee_detail.html', {'employee': employee, 'questions': questions, 'average_result': average_result})


@login_required
def interview_by_company(request):
    try:
        company_id = request.user.company_set.first().id
        interviews = JobInterview.objects.filter(company=company_id)
        if request.user.company_set.filter(id=company_id) == request.user:
            return render(request, 'consultant/interview_by_company.html', {'interviews': interviews})
        else:
            return render(request, 'consultant/interview_by_company.html', {'interviews': interviews})
    except:
        return render(request, 'consultant/interview_by_company.html', {'error': 'You are not a consultant'})
    

@login_required
def done_interview(request):
    return render(request, 'consultant/done_questins.html')








def error_404(request, exception):
    return render(request, 'consultant/404.html')

consultant/templates/consultant/create_interview.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% if success %}
<p>Interview created successfully!</p>
{% endif %}

{% if error %}
<p>{{ error }}</p>
{% endif %}




<section id="createAssessment" class="">

    <div class="row">

        <div class="row">
            <form method="post" enctype="multipart/form-data" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <h4>Create Assessment</h4>
                    <div class="row">
                        <p>Please download Excel file in the below link to enter applicatnts data before upload it in this form.  <a href="{% static 'consultant/example.xlsx' %}" class="">Download Example Excel File</a></p>
                        
                    </div>
                    <div class="input-field col s12 m3 l3">
                        <input placeholder="Job Title" id="title" type="text" class="validate" name="title" required>
                        <label for="jobTitle">Job Title</label>
                    </div>
                    <div class="input-field col s12 m3 l3">
                        <input placeholder="Number Of Questions" id="questionCount" type="number"
                            name="number_of_questions" required class="validate">
                        <label for="questionCount">Number Of Questions</label>
                    </div>
                    <!-- <div class="input-field col s12 m3 l3">
                            <input placeholder="Duration Time" id="duration" type="number" class="validate">
                            <label for="duration">Duration Time</label>
                        </div> -->
                    <!-- <div class="input-field col s12 m3 l3">
                            <input placeholder="Validate Time" id="validateTime" type="number" class="validate">
                            <label for="validateTime">Validate Time</label>
                        </div> -->
                    <div class="file-field input-field col s12 m6 l6">
                        <div class="btn">
                            <span>Upload Employees Excel File</span>
                            <input type="file" required name="employees">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>

                        
                    </div>
                   
                </div>

                <div class="row ">
                    <button type="submit" class="waves-effect waves-light btn">Submit & Send Emails <i
                            class="material-icons left">save</i></button>
                </div>

            </form>
        </div>

    </div>
</section>

{% endblock content %}

consultant/templates/consultant/done_questins.html
{% extends "base.html" %}


{% block content %}

<p class="successMessage">
    Thank you for your time. Your answers have been recorded.
</p>

{% endblock content %}

consultant/templates/consultant/employee_detail.html
{% extends "base.html" %}

{{ questions|length }}

{% block content %}


<section id="dashbard" class="">
    <div class="row">
        <p>Assessment of {{ employee.name }} for {{ questions.0.interview.title }}</p>
        <table class="striped">
            <thead>
                <tr>
                    <th>question</th>
                    <th>Answer</th>
                    <th>Result</th>
                </tr>
            </thead>

            <tbody>
                {% for question in questions %}
                <tr>
                    <td>{{ question }}</td>
                    <td>{{ question.answer }}</td>
                    <td>{{ question.result }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">You have not jobs yet!</td>
                </tr>
                {% endfor %}
                {% if total_result != 0 %}
                <tr>
                    <td colspan="2">Total Result</td>
                    <td>{{ average_result }}%</td>
                </tr>
                {% endif %}
            </tbody>
        </table>

    </div>
</section>

{% endblock content %}

consultant/templates/consultant/home.html
{% extends "base.html" %}


{% for interview in interviews %}
    
    <p>{{ interview.title }}</p>
    
    
    <p>{{ interview.employees.all|length }}</p>

    {% empty %}

    <p>You have not jobs yet!</p>
{% endfor %}





{% block content %}


<section id="dashbard" class="">
    <a class="waves-effect waves-light btn">Create new Assessment <i class="material-icons left">add</i></a>
    <div class="row">
        <p>You have {{ interviews|length }} Assessment</p>
        <table class="striped">
            <thead>
                <tr>
                    <th>Job Title</th>
                    <th>Item Name</th>
                    <th>Item Price</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td><a href="#">Alvin</a></td>
                    <td>Eclair</td>
                    <td>$0.87</td>
                </tr>
                <tr>
                    <td><a href="#">Alan</a></td>
                    <td>Jellybean</td>
                    <td>$3.76</td>
                </tr>
                <tr>
                    <td><a href="#">Jonathan</a></td>
                    <td>Lollipop</td>
                    <td>$7.00</td>
                </tr>
            </tbody>
        </table>

    </div>
</section>

{% endblock content %}

consultant/templates/consultant/interview_by_company.html
{% extends "base.html" %}


{% block content %}


{% if error %}
    <p class="error">You don't have permission to access this page</p>

{% else %}

<section id="dashbard" class="">
    <a href="{% url 'consultant:create_interview' %}" class="waves-effect waves-light btn">Create new Assessment <i class="material-icons left">add</i></a>
    <div class="row">
        <p>You have {{ interviews|length }} Assessment</p>
        <table class="striped">
            <thead>
                <tr>
                    <th>Job Title</th>
                    <th>Count of Employees</th>
                </tr>
            </thead>

            <tbody>
                {% for interview in interviews %}
                <tr>
                    <td><a href="{% url 'consultant:interview_detail'  interview.id %}">{{ interview.title }}</a></td>
                    <td>{{ interview.employees.all|length }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">You have not jobs yet!</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endif %}
{% endblock content %}

consultant/templates/consultant/interview_detail.html
{% extends "base.html" %}


{% block content %}
  
<section id="assessmentResult" class="">
    
    <div class="row">
        <h3>Result for Assessment of {{ interview.title }}</h3>
        <p>Number of Employees: {{ employees|length }}</p>
        <table class="striped">
            <thead>
                <tr>
                    <th>Person name</th>
                    <th>Finish Test?</th>
                </tr>
            </thead>

            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><a href="{% url 'consultant:employee_detail' employee.id interview.id %}">{{ employee.name }}</a></td>
                    <td>
                        {% if  employee.is_finished %}
                          Yes
                        {% else %}
                            No
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">You have not jobs yet!</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</section>


{% endblock content %}

consultant/templates/consultant/interview_questions_for_employee.html
{% extends "base.html" %}



{% block content %}

<section id="assessmentForm" class="">
    <div class="row">
        <div class="row">
            <form class="col s12" method="post">
                {% csrf_token %}
                <div class="row">
                    <h4>Assessment Form for {{ employee }}</h4>
                    {% for question in questions %}
                    <div class="input-field col s12 m12 l12">
                        <textarea id="id_question" class="materialize-textarea" required
                            name="question{{ question.id }}"></textarea>
                        <label for="id_question">{{ question }}</label>
                    </div>
                    {% endfor %}
                    <div class="row center">
                        <button type="submit" class="waves-effect waves-light btn">Save <i class="material-icons left">save</i></button>
                    </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}